version: 2

sphinx:
  fail_on_warning: true

conda:
  environment: docs/environment.yaml

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - recommonmark
        - sphinx_rtd_theme
        - prefetch_generator
        - umsgpack