version: 2

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-docs.txt
    - method: pip
      path: .

build:
   os: ubuntu-22.04
   tools:
     python: "3.11"
