comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
coverage:
  status:
    patch:
      default:
        informational: false
    project:
      default:
        threshold: 1%
