# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"_\n\x0b\x41\x63\x63\x65ssToken\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x17\n\x0f\x65xpiration_time\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"\x88\x01\n\x0fRequestAuthInfo\x12)\n\x13\x63lient_access_token\x18\x01 \x01(\x0b\x32\x0c.AccessToken\x12\x1a\n\x12service_public_key\x18\x02 \x01(\x0c\x12\x0c\n\x04time\x18\x03 \x01(\x01\x12\r\n\x05nonce\x18\x04 \x01(\x0c\x12\x11\n\tsignature\x18\x05 \x01(\x0c\"`\n\x10ResponseAuthInfo\x12*\n\x14service_access_token\x18\x01 \x01(\x0b\x32\x0c.AccessToken\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACCESSTOKEN']._serialized_start=14
  _globals['_ACCESSTOKEN']._serialized_end=109
  _globals['_REQUESTAUTHINFO']._serialized_start=112
  _globals['_REQUESTAUTHINFO']._serialized_end=248
  _globals['_RESPONSEAUTHINFO']._serialized_start=250
  _globals['_RESPONSEAUTHINFO']._serialized_end=346
# @@protoc_insertion_point(module_scope)
