# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: averaging.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import runtime_pb2 as runtime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61veraging.proto\x1a\rruntime.proto\"n\n\x0bJoinRequest\x12\x13\n\x0bschema_hash\x18\x02 \x01(\x0c\x12\x12\n\nexpiration\x18\x03 \x01(\x01\x12\x0e\n\x06gather\x18\x04 \x01(\x0c\x12\x13\n\x0b\x63lient_mode\x18\x05 \x01(\x08\x12\x11\n\tgroup_key\x18\x06 \x01(\t\"\x87\x01\n\x11MessageFromLeader\x12\x1a\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0c.MessageCode\x12\x10\n\x08group_id\x18\x02 \x01(\x0c\x12\x18\n\x10suggested_leader\x18\x03 \x01(\x0c\x12\x18\n\x10ordered_peer_ids\x18\x04 \x03(\x0c\x12\x10\n\x08gathered\x18\x05 \x03(\x0c\"|\n\rAveragingData\x12\x1a\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0c.MessageCode\x12\x10\n\x08group_id\x18\x02 \x01(\x0c\x12\x0f\n\x07peer_id\x18\x03 \x01(\x0c\x12\x1c\n\x0btensor_part\x18\x04 \x01(\x0b\x32\x07.Tensor\x12\x0e\n\x06weight\x18\x05 \x01(\x01\"\x11\n\x0f\x44ownloadRequest\">\n\x0c\x44ownloadData\x12\x10\n\x08metadata\x18\x01 \x01(\x0c\x12\x1c\n\x0btensor_part\x18\x02 \x01(\x0b\x32\x07.Tensor*\x86\x03\n\x0bMessageCode\x12\x0b\n\x07NO_CODE\x10\x00\x12\x10\n\x0cREQUEST_JOIN\x10\x01\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x02\x12\x13\n\x0f\x42\x45GIN_ALLREDUCE\x10\x03\x12\x16\n\x12PART_FOR_AVERAGING\x10\x04\x12\x11\n\rAVERAGED_PART\x10\x05\x12\x10\n\x0cNOT_DECLARED\x10\x06\x12\x10\n\x0cNOT_A_LEADER\x10\x07\x12\x17\n\x13\x42\x41\x44_EXPIRATION_TIME\x10\x08\x12\x13\n\x0f\x42\x41\x44_SCHEMA_HASH\x10\t\x12\x10\n\x0c\x42\x41\x44_GROUP_ID\x10\n\x12\x15\n\x11\x44UPLICATE_PEER_ID\x10\x0b\x12\x11\n\rGROUP_IS_FULL\x10\x0c\x12\x19\n\x15NOT_LOOKING_FOR_GROUP\x10\r\x12\x16\n\x12PROTOCOL_VIOLATION\x10\x0e\x12\x12\n\x0eINTERNAL_ERROR\x10\x0f\x12\r\n\tCANCELLED\x10\x10\x12\x13\n\x0fGROUP_DISBANDED\x10\x11\x12\x11\n\rBAD_GROUP_KEY\x10\x12\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'averaging_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGECODE']._serialized_start=494
  _globals['_MESSAGECODE']._serialized_end=884
  _globals['_JOINREQUEST']._serialized_start=34
  _globals['_JOINREQUEST']._serialized_end=144
  _globals['_MESSAGEFROMLEADER']._serialized_start=147
  _globals['_MESSAGEFROMLEADER']._serialized_end=282
  _globals['_AVERAGINGDATA']._serialized_start=284
  _globals['_AVERAGINGDATA']._serialized_end=408
  _globals['_DOWNLOADREQUEST']._serialized_start=410
  _globals['_DOWNLOADREQUEST']._serialized_end=427
  _globals['_DOWNLOADDATA']._serialized_start=429
  _globals['_DOWNLOADDATA']._serialized_end=491
# @@protoc_insertion_point(module_scope)
