# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dht.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import  auth_pb2 as auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdht.proto\x1a\nauth.proto\"\x1b\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\x0c\"X\n\x0bPingRequest\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x10.RequestAuthInfo\x12\x17\n\x04peer\x18\x02 \x01(\x0b\x32\t.NodeInfo\x12\x10\n\x08validate\x18\x03 \x01(\x08\"m\n\x0cPingResponse\x12\x1f\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x11.ResponseAuthInfo\x12\x17\n\x04peer\x18\x02 \x01(\x0b\x32\t.NodeInfo\x12\x10\n\x08\x64ht_time\x18\x04 \x01(\x01\x12\x11\n\tavailable\x18\x05 \x01(\x08\"\xa1\x01\n\x0cStoreRequest\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x10.RequestAuthInfo\x12\x0c\n\x04keys\x18\x02 \x03(\x0c\x12\x0f\n\x07subkeys\x18\x03 \x03(\x0c\x12\x0e\n\x06values\x18\x04 \x03(\x0c\x12\x17\n\x0f\x65xpiration_time\x18\x05 \x03(\x01\x12\x10\n\x08in_cache\x18\x06 \x03(\x08\x12\x17\n\x04peer\x18\x07 \x01(\x0b\x32\t.NodeInfo\"[\n\rStoreResponse\x12\x1f\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x11.ResponseAuthInfo\x12\x10\n\x08store_ok\x18\x02 \x03(\x08\x12\x17\n\x04peer\x18\x03 \x01(\x0b\x32\t.NodeInfo\"T\n\x0b\x46indRequest\x12\x1e\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x10.RequestAuthInfo\x12\x0c\n\x04keys\x18\x02 \x03(\x0c\x12\x17\n\x04peer\x18\x03 \x01(\x0b\x32\t.NodeInfo\"\x83\x01\n\nFindResult\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.ResultType\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x17\n\x0f\x65xpiration_time\x18\x03 \x01(\x01\x12\x18\n\x10nearest_node_ids\x18\x04 \x03(\x0c\x12\x18\n\x10nearest_peer_ids\x18\x05 \x03(\x0c\"f\n\x0c\x46indResponse\x12\x1f\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x11.ResponseAuthInfo\x12\x1c\n\x07results\x18\x02 \x03(\x0b\x32\x0b.FindResult\x12\x17\n\x04peer\x18\x03 \x01(\x0b\x32\t.NodeInfo*D\n\nResultType\x12\r\n\tNOT_FOUND\x10\x00\x12\x11\n\rFOUND_REGULAR\x10\x01\x12\x14\n\x10\x46OUND_DICTIONARY\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dht_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESULTTYPE']._serialized_start=836
  _globals['_RESULTTYPE']._serialized_end=904
  _globals['_NODEINFO']._serialized_start=25
  _globals['_NODEINFO']._serialized_end=52
  _globals['_PINGREQUEST']._serialized_start=54
  _globals['_PINGREQUEST']._serialized_end=142
  _globals['_PINGRESPONSE']._serialized_start=144
  _globals['_PINGRESPONSE']._serialized_end=253
  _globals['_STOREREQUEST']._serialized_start=256
  _globals['_STOREREQUEST']._serialized_end=417
  _globals['_STORERESPONSE']._serialized_start=419
  _globals['_STORERESPONSE']._serialized_end=510
  _globals['_FINDREQUEST']._serialized_start=512
  _globals['_FINDREQUEST']._serialized_end=596
  _globals['_FINDRESULT']._serialized_start=599
  _globals['_FINDRESULT']._serialized_end=730
  _globals['_FINDRESPONSE']._serialized_start=732
  _globals['_FINDRESPONSE']._serialized_end=834
# @@protoc_insertion_point(module_scope)
